// Extracted & simplified genres from: https://en.wikipedia.org/wiki/List_of_video_game_genres
module.exports = [
  'Platform',
  'Shooter',
  'Fighting',
  'Beat \'em up',
  'Stealth',
  'Survival',
  'Battle Royale',
  'Rhythm',
  'Survival Horror',
  'Metroidvania',
  'Text',
  'Graphic',
  'Visual Novel',
  'Interactive Movie',
  'Real-time 3D',
  'Action RPG',
  'MMORPG',
  'Roguelike',
  'Tactical RPG',
  'Sandbox RPG',
  'JRPG',
  'Monster Collection',
  'Simulation',
  '4X',
  'Artillery',
  'Auto Battler',
  'MOBA',
  'Real-Time Strategy',
  'Real-Time Tactics',
  'Tower Defense',
  'Turn-Based Strategy',
  'Turn-Based Tactics',
  'Wargame',
  'Racing',
  'Sports',
  'Competitive',
  'Board Game',
  'Card Game',
  'Casual',
  'Horror',
  'Logic',
  'MMO',
  'Mobile',
  'Party',
  'Programming',
  'Trivia',
  'Idle',
  'Narrative',
  'Sandbox',
  'Creative',
  'Open World',
  'Puzzle',
  'Mystery'
];
