version: 2.1
jobs:
  build:
    working_directory: ~/item-description
    docker:
      - image: circleci/node:12.14.0
        environment:
          DBNAME: item_descriptions
          MDBPORT: 3306
          NODE_ENV: test
          CI: true
      - image: mariadb:10.3
        environment:
          MYSQL_ROOT_PASSWORD: ci_password
          MYSQL_DATABASE: item_descriptions_test
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: wait-for-mariadb
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: test
          command: npm run test
